spring.application.name=DevBoard
spring.datasource.url=jdbc:postgresql://localhost:5432/DevBoard
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Flyway config
spring.flyway.enabled=false

#Keycloak
spring.security.oauth2.client.registration.Devboard-project-management.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.Devboard-project-management.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.Devboard-project-management.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.Devboard-project-management.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.Devboard-project-management.redirect-uri=http://localhost:3000/*
spring.security.oauth2.client.provider.Devboard-project-management.issuer-uri=http://127.0.0.1:8334/realms/OAuth2-devboard

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:8334/realms/OAuth2-devboard


#kafka connection
spring.kafka.bootstrap-servers=localhost:9092

#Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
#acks=all: the producer waits until the broker confirms the write.
spring.kafka.producer.acks=all

#Consumer
spring.kafka.consumer.group-id=devboard-notification
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.satyam.DevBoard.event