spring.application.name=DevBoard
spring.datasource.url=jdbc:postgresql://localhost:5432/DevBoard
spring.datasource.username=postgres
spring.datasource.password=20017705m
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Flyway config
spring.flyway.enabled=false

#Keyclock
spring.security.oauth2.client.registration.Devboard-project-management.client-id=Devboard-project-management
spring.security.oauth2.client.registration.Devboard-project-management.client-secret=p9sDHT1EnazinGeWeVjAevBeet8lykaxcOX7hFkGUUBOxm3n0LRwNi3s7riBHa0PQfqC2rfxBZkLoduGMMiiB0
spring.security.oauth2.client.registration.Devboard-project-management.scope=openid,profile,roles,email
spring.security.oauth2.client.registration.Devboard-project-management.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.Devboard-project-management.redirect-uri=http://localhost:3000/*
spring.security.oauth2.client.provider.Devboard-project-management.issuer-uri=http://127.0.0.1:8334/realms/OAuth2-devboard