### Create Organization
POST http://localhost:8080/api/v1/organizations
Content-Type: application/json

{
  "name": "Acme Corp",
  "slug": "acme-corp",
  "location": "Nagpur, India",
  "timeZone": "Asia/Kolkata"
}

### Get Organization
@org_id = bc2edd1b-ad72-47fd-8b49-39640eb64ddd
GET http://localhost:8080/api/v1/organizations/{{org_id}}

### Create User
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "Satyam Kalihari",
  "email": "satyam@acme.com",
  "phone": "8349132468",
  "avatarUrl": "sads/dsahdjsa/sadsad.com"
}

### Get User
@user_id = a7f372e2-6bd2-4a26-bac0-62ed64edd623
GET http://localhost:8080/api/v1/users/{{user_id}}


### Get All Users
GET http://localhost:8080/api/v1/users

### Update a user
PATCH http://localhost:8080/api/v1/users/b9abce1d-716d-4275-a384-12d900c10cfc
Content-Type: application/json

{
  "name": "oBITO kalihari"
}

### Delete a user
DELETE http://localhost:8080/api/v1/users/b9abce1d-716d-4275-a384-12d900c10cfc


### Create OrgMember
POST http://localhost:8080/api/v1/org_members
Content-Type: application/json

{
  "orgId": "bc2edd1b-ad72-47fd-8b49-39640eb64ddd",
  "userId": "a7f372e2-6bd2-4a26-bac0-62ed64edd623",
  "role": "MEMBER"
}

### Get All OrgMembers
@orgMember_id = 045e21d3-7d4c-4453-8a22-f988a9ce41eb
GET http://localhost:8080/api/v1/org_members/4112a02e-ce78-4f17-bfd2-9477ad07f50a

### Delete OrgMember
DELETE http://localhost:8080/api/v1/org_members/045e21d3-7d4c-4453-8a22-f988a9ce41eb