### Create Project
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "name": "Project 2",
  "orgId": "bc2edd1b-ad72-47fd-8b49-39640eb64ddd",
  "userId": "a7f372e2-6bd2-4a26-bac0-62ed64edd623",
  "description": "Testing to create a 2nd project",
  "status": "PENDING",
  "startDate":"2026-06-07",
  "targetDate": "2026-11-07"
}

### Get Project By ID
@pro_id = 8d007c26-ec88-47ca-b44e-2fae905a9d64
GET http://localhost:8080/api/v1/projects

### Update Project
PATCH http://localhost:8080/api/v1/projects/{{pro_id}}
Content-Type: application/json

{
  "startDate":"2026-12-08",
  "targetDate": "2027-11-09"
}

### Delete Project
DELETE http://localhost:8080/api/v1/projects/{{pro_id}}